spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/datashare
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  sql:
    init:
      mode: always
      
security:
  jwt:
    secret: "MaCleSuperSecretePourSignerLesTokens123456789012345"
    expiration: 3600000
